config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => Rails.application.secrets[:default_url_options]
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  authenticated :admin_user do
    mount DelayedJobWeb, at: "/delayed_job"
  end

  devise_scope :user do
    scope :users, as: :users do
      post 'pre_otp', to: 'users/sessions#pre_otp'
    end
  end

  root to: "deploy#index"
  get "/deploy" => "deploy#index"
  get "/deploy/:deployment_id" => "deploy#show"


  namespace :users do
    get    '/two_factor' => 'two_factors#show', as: 'user_two_factor'
    post   '/two_factor' => 'two_factors#create'
    #delete '/two_factor' => 'two_factors#destroy'
  end

  resources :environments, only: [:show], param: :environment_id
  scope '/environments/:environment_id', as: :environment do
    resources :config_files do
      resources :versions, only: [:index, :show]
    end
    resources :logs, only: :index
    get "/dispose" => "environments#dispose", as: :dispose
    get "/migrations" => "environments#migrations"
    get '/migration/:migration_id' => "environments#migration_show"

    get '/kube_status' => "kube_status#index"
  end

  namespace :api do
    resources :deployments, only: [:show, :create] do
      post "redeployment", action: :redeployment
    end

    resources :migrations, only: [:create, :destroy, :show]

    resources :publishers do
       resources :deploy_environments, only: [:index]
    end

    resources :deploy_environments, only: [:index, :show, :destroy] do
      get "deployments", action: :load_more_deployments
      get "migrations", action: :load_more_migrations
      post :scale
      #delete "/delete_deployements" => "deploy_environments#destroy"
      get "validate_config_file", action: :validate_config_file
      post "clone_as_pr", action: :clone_as_pr
    end

    resources :logs, only: [:show]
  end

  ActiveAdmin.routes(self)
end

app/models/config_file.rb
class ConfigFile < ApplicationRecord
	acts_as_paranoid
  belongs_to :deploy_environment

  audited

  before_save do |config_file|
    config_file.value = config_file.value.gsub("\r", "") if config_file.value
  end
end

app/controllers/config_files_controller.rb
class ConfigFilesController < ApplicationController
  before_action :authenticate_user!,:unconfirmed_mfa!

  before_action :load_current_environment
  def load_current_environment
    @current_deploy_environment = current_user.deploy_environments.find(params[:environment_id])
  end

  def new
    @config_file = @current_deploy_environment.config_files.new
  end

  def index
  	@config_files = @current_deploy_environment.config_files
  end

  def show
  	@config_file = @current_deploy_environment.config_files.find(params[:id])
  end

  def create
    @config_file = @current_deploy_environment.config_files.build(value: params[:config_file][:value], path: params[:config_file][:path])
    if @config_file.save
      redirect_to action: "show", id: "#{@config_file.id}"
    else
      render action: "new"
    end
  end

  def update
    @config_file = @current_deploy_environment.config_files.find(params[:id])
    if @config_file.update(value: params[:config_file][:value], path: params[:config_file][:path])
      redirect_to action: "show", id: "#{@config_file.id}"
    else
      render action: "new"
    end
  end

  def destroy
    @config_file = @current_deploy_environment.config_files.find(params[:id])
    @config_file.destroy
    redirect_to action: "index", deploy_environment_id: "#{@current_deploy_environment.id}"
  end

  def edit
    @config_file = @current_deploy_environment.config_files.find(params[:id])
  end
end

app/views/config_files/edit.html.erb
<div class="config-file">
  <h3>Edit Config File #<%= "#{@config_file.id}" %></h3>
  <%= form_for @config_file, url: environment_config_file_path(current_deploy_environment, @config_file) do |f| %>
    <%= f.label :path, class: "config-file__label" %>
    <%= f.text_field :path, class: "config-file__input" %>

    <%= f.label :value, class: "config-file__label" %>
    <%= f.text_area :value, size: "24x35", class: "config-file__input" %>

    <%= f.submit "Update", class: "config-file__button" %>
  <% end %>
</div>

app/views/config_files/index.html.erb
<div class="deployment">
  <%= render partial: "layouts/header" %>
  <h3 class="deployment-heading" >Config Files</h3>
  <h4 class="deployment-redeploy-button"><%= link_to "New Config File", new_environment_config_file_path(current_deploy_environment) %></h4>
  <table class="deployment-table deployment-table-with-heading">
  	<thead>
  	  <tr>
  	  	<th>Path</th>
  	  	<th>Value</th>
  	  </tr>
  	</thead>
  	<tbody>
  	  <% @config_files.each do |config_file| %>
  	    <tr>
  	      <td><%= link_to config_file.path, environment_config_file_path(current_deploy_environment, config_file) %></td>
  	      <td><pre class="config-file-value"><%= config_file.value %></pre></td>
  	    </tr>
  	  <%end%>
  	</tbody>

  </table>
<!--   <div id="container">
  </div>
  <script type="text/javascript">
    blackKnight.environmentPage(document.getElementById("container"), <%= current_deploy_environment.id %>)
  </script> -->
</div>

app/views/config_files/new.html.erb
<div class="config-file">
  <h3>New Config File</h3>
  <%= form_for @config_file, url: environment_config_files_path(current_deploy_environment) do |f| %>

    <%= f.label :path, class: "config-file__label" %>
    <%= f.text_field :path, class: "config-file__input" %>

    <%= f.label :value, class: "config-file__label" %>
    <%= f.text_area :value, size: "24x35", class: "config-file__input" %>

    <%= f.submit "Create", class: "config-file__button" %>
  <% end %>
</div>

app/views/config_files/show.html.erb
<div class="deployment config-file">
	<%= render partial: "layouts/header" %>
	<h3 class="deployment-heading config-file__heading">Config File #<%= @config_file.id %></h3>
	<h4 class="config-file__delete"><%= link_to "Delete", environment_config_file_path(current_deploy_environment, @config_file.id), data: {method: "delete", confirm: "Are you sure?"} %></h4>
	<h4 class="config-file__edit"><%= link_to "Edit", edit_environment_config_file_path(current_deploy_environment, @config_file.id) %></h4>

	<table class="deployment-table deployment-table-without-heading">
		<tbody>
			<tr>
				<td>Path</td>
				<td>
                    <pre class="config-file-path"><%= @config_file.path %></pre>
				</td>
			</tr>
			<tr>
				<td>Updated at</td>
                <td><pre class="config-file-update"><%= @config_file.updated_at %></pre></td>
			</tr>
			<tr>
				<td>Value</td>
				<td><pre class="config-file-value"><%= @config_file.value %></pre></td>
            </tr>
			<tr>
				<td>Version</td>
        <td>
          <%= select_tag("versions",options_for_select(@config_file.audits.select(:version).each_with_index.map{|rec| rec.version},@config_file.audits.maximum(:version)),:onchange => "navigateToVersion()")%>
        </td>
            </tr>
		</tbody>
	</table>
</div>
<script>
  function navigateToVersion() {
    var selectedVersion = document.getElementById("versions").value;
    var getSelectedConfigValue = <%= @config_file.id %> + "/versions/"+ selectedVersion;
    $.get(getSelectedConfigValue, function(data){
      $('.config-file-value').text(data['value']);
      $('.config-file-path').text(data['path']);
    });
  };
</script>