config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => Rails.application.secrets[:default_url_options]
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  authenticated :admin_user do
    mount DelayedJobWeb, at: "/delayed_job"
  end

  devise_scope :user do
    scope :users, as: :users do
      post 'pre_otp', to: 'users/sessions#pre_otp'
    end
  end

  root to: "deploy#index"
  get "/deploy" => "deploy#index"
  get "/deploy/:deployment_id" => "deploy#show"


  namespace :users do
    get    '/two_factor' => 'two_factors#show', as: 'user_two_factor'
    post   '/two_factor' => 'two_factors#create'
    #delete '/two_factor' => 'two_factors#destroy'
  end

  resources :environments, only: [:show], param: :environment_id
  scope '/environments/:environment_id', as: :environment do
    resources :config_files do
      resources :versions, only: [:index, :show]
    end
    resources :logs, only: :index
    get "/dispose" => "environments#dispose", as: :dispose
    get "/migrations" => "environments#migrations"
    get '/migration/:migration_id' => "environments#migration_show"

    get '/kube_status' => "kube_status#index"
  end

  namespace :api do
    resources :deployments, only: [:show, :create] do
      post "redeployment", action: :redeployment
    end

    resources :migrations, only: [:create, :destroy, :show]

    resources :publishers do
       resources :deploy_environments, only: [:index]
    end

    resources :deploy_environments, only: [:index, :show, :destroy] do
      get "deployments", action: :load_more_deployments
      get "migrations", action: :load_more_migrations
      post :scale
      #delete "/delete_deployements" => "deploy_environments#destroy"
      get "validate_config_file", action: :validate_config_file
      post "clone_as_pr", action: :clone_as_pr
    end

    resources :logs, only: [:show]
  end

  ActiveAdmin.routes(self)
end

app/views/layouts/_header.html.erb
  <h2 class="deployment-publisher-name"><%= "#{current_deploy_environment.name} (#{current_deploy_environment.publisher.name})" %></h2>
  <p>
    <%= link_to "Deploys", "/environments/#{current_deploy_environment.id}", class: "deployment-environment-name" %>  |

    <% if current_deploy_environment.migratable? %>
      <%= link_to "Migrations", "/environments/#{current_deploy_environment.id}/migrations", class: "deployment-environment-name" %> |
    <% end %>

    <%= link_to "Config Files", environment_config_files_path(current_deploy_environment.id), class: "deployment-environment-name" %>  |
    <%= link_to "Logs", environment_logs_path(current_deploy_environment.id), class: "deployment-environment-name" %>
    <% if current_deploy_environment.disposable? %>
    | <%= link_to "Dispose", environment_dispose_path(current_deploy_environment), class: "deployment-environment-name" %>
    <% end %>
    |
    <%= link_to "Kube Status", environment_kube_status_path(current_deploy_environment.id), class: "deployment-environment-name" %>
  </p>

app/views/layouts/_left_bar.html.erb
<div class="leftbar-user-details">
  <%= current_user.name %> | <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
</div>
<div class="leftbar-search">
  <input type="text" onchange="blackKnight.searchPub(event)" placeholder="Search..." />
</div>
<ul class="leftbar-publishers">
  <% publishers.order(:name).each do |publisher| %>
  <li class="leftbar-publisher <%= 'publisher-open' if publisher.id == current_publisher_id %>">
    <%= link_to publisher.name, "javascript:void(0)", class: "leftbar-publisher-name" %>
    <% publisher.deploy_environments.order(:name).each do |deploy_env| %>
      <%= link_to deploy_env.name, "/environments/#{deploy_env.id}",{ "data-publisher":"#{deploy_env.name}", class: "leftbar-publisher-environment #{'deploy-environment-selected' if deploy_env == current_deploy_environment}" }%>
    <% end %>
  </li>
  <% end %>
</ul>
<script>
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Black Knight, Deployments made Easy!</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
    <div class="layout-leftbar leftbar">
      <a href="<%= root_path %>">
	<img class="leftbar-logo" src="<%= image_path('logo.png') %>"/>
      </a>
      <%= render partial: "layouts/left_bar" if current_user %>
    </div>
    <div class="layout-content"><%= yield %></div>
    <script type="text/javascript">
      blackKnight.publishersMenu();
      blackKnight.searchPub();
    </script>
  </body>
</html>